services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: mongodb://mongo_db:27017/egrul
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: